# Site
repository: SCVA/jekyll_cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sebastian Camilo Vanegas Ayala
title: Ingeniero de Sistemas
email: scvanegasa@correo.udistrital.edu.co
website: https://github.com/SCVA/jekyll_cv

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: scva97
github_username:  SCVA
facebook_username: sebastiancamilo.vanegasayala
instagram_username: sebasvanegas14
linkedin_username: sebastian-camilo-vanegas-ayala-6915b678
pinterest_username: scva9708
orcid_username: 0000-0002-8610-9765

# Additional icon links
additional_links:
- title: CvLAC
  icon: fas fa-user
  url: https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000155010

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Acerca de mi
about_profile_image: https://media-exp1.licdn.com/dms/image/C4E03AQGM6b1Hc-OzLw/profile-displayphoto-shrink_200_200/0/1590683795213?e=1635984000&v=beta&t=CJfIpBZJfcLWBhZ-EFZtofuT2XUGU1OjSXzC0jb5uks
about_content: | # this will include new lines to allow paragraphs
  Hola, mi nombre es Sebastian Vanegas. •	Como Ingeniero de Sistemas de la Universidad Distrital Francisco José de Caldas espero aportar mucho a la ciudad y al país en materia de investigación y desarrollo, soportándome en los conocimientos y apoyo brindado por el plantel académico y la comunidad universitaria.
content:
  - title: Formación Académica # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad Distrital Francisco José de Caldas
        caption: 2015 - 2020
        sub_title: Ingeniero de Sistemas
        quote: >
          La Universidad Distrital Francisco José de Caldas es una universidad pública colombiana. Su nombre es honor a Francisco José de Caldas, prócer de la independencia de Colombia.
        description: | # this will include new lines to allow paragraphs          
          El tiempo en la Universidad Distrital me permitió formarme como Ingeniero de Sistemas, apropiando muchos conocimientos en diversas áreas de la computación, la inteligencia artificial, ingeniería de software, bases de datos y gestión de proyectos. Acompañada mi formación con una enseñanza de valores morales en pro de la sociedad, el trabajo en equipo y el crecimiento personal.
          
          Titulado mediante trabajo de grado de carácter meritorio acerca de la predicción de humedad y temperatura en invernaderos usando métodos de optimización para conjuntos difusos.
        link: https://repository.udistrital.edu.co/handle/11349/25654
        link_text: Tesis
      - layout: left
        title: SENA - Servicio Nacional de Aprendizaje
        caption: 2013-2014
        sub_title: Técnico en contabilización de operaciones comerciales y financieras
        quote: >
          Somos un establecimiento público del orden Nacional y con autonomía administrativa, adscrito al Ministerio del Trabajo.
        description: | # this will include new lines to allow paragraphs          
          La formación como Técnico en contabilización de operaciones comerciales y financieras me permitió adquirir habilidades acerca de los procesos contables y administrativos al interior de las empresas con un acercamiento al sector laboral directo en un año de prácticas.
          
  - title: Experiencia Laboral # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: Universidad Distrital Francisco José de Caldas
        link: https://www.udistrital.edu.co/inicio
        # link_text: boringcompany.com
        sub_title: Ingeniero de Sistemas - CPS
        caption: Agosto 2020 - Presente
        quote: >
          Contribuir a que la Universidad sea factor de desarrollo espiritual y material del Distrito Capital de Bogotá.
        description: | # this will include new lines to allow paragraphs
          Apoyo en actividades misionales en gestión docencia y desarrollo de contenidos web, aportando los conocimientos de la Ingeniería en el desarrollo de artefactos que contribuyan a los procesos de contratación docente, vigilancia y control de las actividades docentes y de apoyo a la decanatura de la Facultad de Ingeniería. 
      - layout: right
        title: CAFÉ Y EQUIPOS LTDA.
        link: http://www.cafeyequiposcolombia.com/
        # link_text: boringcompany.com
        sub_title: Asesor de Sistemas
        caption: 2017 - 2018
        quote: >
          Somos una empresa dedicada a la investigación del café y al desarrollo y fabricación de equipos para la industria del café desde hace más de 20 años.
        description: | # this will include new lines to allow paragraphs
          Apoyo en actividades de mantenimiento de equipos tecnológicos, manejo de archivos, diseño y aplicación de software y en el rol de Webmaster.
              
  - title: Artículos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Environment humidity and temperature prediction in agriculture using Mamdani inference systems
        link: http://ijece.iaescore.com/index.php/IJECE/article/view/24000
        link_text: Enlace
        description: | # this will include new lines to allow paragraphs
          This paper presents the results of a humidity and temperature prediction model in the environment for agriculture, using diffuse sets and optimizing their parameters by heuristic methods, such as genetic algorithms, and exact methods such as Quasi-Newton. It has been identified that non-specialized users could have difficulties in understanding the system dynamics and the behavior of variables over time. The aim of this research is obtain models with a high level of interpretability and accuracy that allows predicting the temperature and humidity values for the environment. The use of fuzzy logic to present a solution has great advantages as this system is highly rated for interpretability. Furthermore, by relating the obtained values for environment humidity and temperature to qualitative categories as high, medium or low, it allows non-specialized users to have a better understanding of the system dynamics. Two optimization techniques are applied to two different diffuse sets that allow the prediction of the humidity and temperature. It is found that the best implementation involves a Mamdani fuzzy inference system optimized with Quasi-Newton algorithm that uses a set of initial values attained through a previous optimization process with a genetic algorithm.
      - layout: top-middle
        title: Gestión del ambiente del invernadero mediante un microcontrolador electrónico para el cultivo de vegetales
        link: https://www.revistaespacios.com/a20v41n19/20411901.html
        link_text: Enlace
        description: | # this will include new lines to allow paragraphs
          This document presents the results of a small-scale prototype of a greenhouse supported by electronic devices and made with recyclable materials. The main objective of the proposed model is to establish a prototype of a controlled environment through the use of sensors and actuators managed by a microcontroller to regulate weather conditions such as temperature and both environmental and soil moisture, applied to pilot crops of common radish and kidney beans. The results obtained in conventional sowing and using the prototype implemented are described and compared.

  - title: Software
    layout: list
    content:
      - layout: top-middle
        title: PREDHYT
        description: | # this will include new lines to allow paragraphs
          Aplicación para predicción de humedad y temperatura en ambiente e invernaderos usando métodos de optimización para conjuntos difusos. Se desarrollan 4 propuestas de tipo sugeno optimizadas por el método heurístico de algoritmos genéticos y el método exacto cuasi-newton. Presenta la predicción de manera gráfica acompañada de la interpretación dada a la misma, en términos cualitativos para fácil uso por el usuario.
          
          ![Visual](images/software "Visual")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
