# Site
repository: SCVA/jekyll_cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sebastian Camilo Vanegas Ayala
title: Ingeniero de Sistemas
email: scvanegasa@correo.udistrital.edu.co
website: https://github.com/SCVA/jekyll_cv

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: scva97
github_username:  SCVA
facebook_username: sebastiancamilo.vanegasayala
instagram_username: sebasvanegas14
linkedin_username: sebastian-camilo-vanegas-ayala-6915b678
pinterest_username: scva9708
orcid_username: 0000-0002-8610-9765

# Additional icon links
additional_links:
- title: CvLAC
  icon: fas fa-user
  url: https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000155010

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Acerca de mi
about_profile_image: https://media-exp1.licdn.com/dms/image/C4E03AQGM6b1Hc-OzLw/profile-displayphoto-shrink_200_200/0/1590683795213?e=1635984000&v=beta&t=CJfIpBZJfcLWBhZ-EFZtofuT2XUGU1OjSXzC0jb5uks
about_content: | # this will include new lines to allow paragraphs
  Hola, mi nombre es Sebastian Vanegas. •	Como Ingeniero de Sistemas de la Universidad Distrital Francisco José de Caldas espero aportar mucho a la ciudad y al país en materia de investigación y desarrollo, soportándome en los conocimientos y apoyo brindado por el plantel académico y la comunidad universitaria.
content:
  - title: Formación Académica # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad Distrital Francisco José de Caldas
        caption: 2015 - 2020
        sub_title: Ingeniero de Sistemas
        quote: >
          La Universidad Distrital Francisco José de Caldas es una universidad pública colombiana. Su nombre es honor a Francisco José de Caldas, prócer de la independencia de Colombia.
        description: | # this will include new lines to allow paragraphs          
          El tiempo en la Universidad Distrital me permitio formarme como Ingeniero de Sistemas, apropiando muchos conocimientos en diversas áreas de la computación, la inteligencia artificial, ingeniería de software, bases de datos y gestión de proyectos. Acompañada mi formación con una enseñanza de valores morales en pro de la sociedad, el trabajo en equipo y el crecimiento personal.
          
          Titulado mediante trabajo de grado de caracter meritorio acerca de la predicción de humedad y temperatura en invernaderos usando métodos de optimización para conjuntos difusos.
        link: https://repository.udistrital.edu.co/handle/11349/25654
      - layout: left
        title: SENA - Servicio Nacional de Aprendizaje
        caption: 2013-2014
        sub_title: Técnico en contabilización de operaciones comerciales y financieras
        quote: >
          Somos un establecimiento público del orden Nacional y con autonomía administrativa, adscrito al Ministerio del Trabajo.
        
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
